providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "nginx"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cp nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"